//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Content type.
	/// </summary>
	public class ContentType
	{	      		
		public const int Auto = 0;				//自动(iOS为自动，安卓仅为Text)
		public const int Text = 1; 				//文字分享
		public const int Image = 2;				//图文分享
		public const int Webpage = 4;			//链接分享
		public const int Music = 5;				//音乐分享 
		public const int Video = 6;				//视频分享 
		public const int App = 7; 				//应用分享
		public const int File = 8;				//附件分享
		public const int Emoji = 9;             //表情分享

#if UNITY_ANDROID
		public const int MiniProgram = 11;              //微信小程序 v3.6.3
        public const int QQ_MINI_PROGRAM = 15;          //qq小程序
#elif UNITY_IPHONE
		public const int MiniProgram = 10;              //微信小程序 v3.6.3
		public const int Message = 11;           //快手-分享到私信

#endif
		public const int OpenMiniProgram = 12;          //打开微信小程序 v3.6.3

	}

}

